identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - app
    - id
    - URL
    - url
    - GlobalAPIKey
  allowed_symbols: [A-Za-z0-9\-_]
reporter: "xcode"
